FROM node:22.2.0

WORKDIR /app
RUN npm install -g pnpm@9.1.2

COPY .npmrc .
COPY package.json .
COPY ./orbital-ui-* .
RUN pnpm install
COPY tsconfig.json .
COPY tsconfig.app.json .
COPY tailwind.config.js .
COPY angular.json .
CMD ["node_modules/.bin/ng", "serve", "--host=0.0.0.0", "--disable-host-check", "--port=80", "--poll=1000"]
