services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
      - /app/obj/
      - /app/bin/
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/app/src
    environment:
      - NODE_ENV=development
    networks:
      - app-network
  caddy:
    image: caddy:2
    container_name: oad.caddy.dev
    ports:
      - "80:80"
      - "4200:4200"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - app-network


networks:
  app-network:
