services:
  db:
    image: postgres:17.1
    container_name: postgres.dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_DB: storieslikegrapes
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    networks:
      - app-network

networks:
  app-network:


