services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/app
    environment:
      - PORT=80
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/app/src
    environment:
      - NODE_ENV=development
    networks:
      - app-network
  caddy:
    image: caddy:2
    container_name: caddy.dev
    ports:
      - "80:80"
      - "4200:4200"
    volumes:
      - ./revproxy/Caddyfile.dev:/etc/caddy/Caddyfile:ro
    networks:
      - app-network


networks:
  app-network:


